[theme]
base="dark"
primaryColor="#00BFFF"  # Sky blue for highlights
backgroundColor="#121212"  # Deep black for main background
secondaryBackgroundColor="#1A237E"  # Dark blue sidebar
textColor="#E0E0E0"  # Light grey for text
font="monospace"
